name: epic-racers # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Epic Racers Extreme
summary: High-speed racing action!
description: Race futuristic vehicles across breathtaking tracks and prove yourself in professional racing leagues.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  epic-racers:
    command: bin/epic-racers-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  epic-racers:
    plugin: dump
    source: .
    organize:
      epic-racers-bin: bin/
